
server:
  port: 8086

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ms_user_schema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
