

server:
  port: 8081

spring:
  application:
    name: USER-SERVICE


  datasource:
    url: jdbc:mysql://localhost:3306/ms_user_schema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #handle multipart file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
project:
  image: Upload/user-img/







#eureka:
#  server:
#    enabled: false