spring:
  application:
    name: RATING-SERVICE
  debug: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 8083





#hi