server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hipradeep/microservice-config
          #default-label: main  # The branch to use, e.g., `main`
          #username: your-github-username  # Optional if private repo
          #password: your-github-token  # Optional if private repo
          clone-on-start: true
